[package]
name = "escpos-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "parsing"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1.21.3"
regex = "1.11.3"
