[workspace]
resolver = "3"
members = [
    "packages/encoding",
    "packages/macros/escpos",
    "packages/macros/encoding",
    "packages/scratch",
    "packages/tools/escpos_build",
    "packages/emulators/tm-t88v",
    "packages/core",
]
