[package]
name = "commands"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfield-struct = "0.11.0"
facet = "0.29.0"
strum = { version = "0.27.2", features = ["derive"] }
winnow = "0.7.13"

[dependencies.escpos-macros]
path = "../macros/escpos"
