[package]
name = "reciptify"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
futures-core = "0.3.31"
futures-util = "0.3.31"
json = "0.12.4"
reqwest = { version = "0.12.24", features = ["json"] }
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["full"] }
thermal = { path = "../core" }
facet = "0.29.0"
facet-pretty = { version = "0.29.0", features = ["alloc"] }
base64 = "0.22.1"
chrono = "0.4.42"
pad = "0.1.6"
unicode-segmentation = "1.12.0"

[dependencies.thermal-encoding]
path = "../encoding"

[dependencies.thermal-emulator-tm-t88v]
path = "../emulators/tm-t88v"
